import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
import { Luckiest_Guy } from 'next/font/google'; 

const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"], 
  variable: "--font-luckiest-guy", 
  weight: "400", 
}); 
*/



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
